### ISSUE TITLE
issue: snippets을 이용한 index.adoc 작성 (상품, 장바구니)

### ISSUE THREAD

**Issue by wocjf0513** [Shimpyo-House/Shimpyo_BE#47]
### Description
> test에서 쓴 restdocs 문법을 이용해 만든 snippets으로 api문서를 꾸밉니다.

### Todo
- [ ] 상품 관련 snippets 정리하기
- [ ] 장바구니 관련 snippets 정리하기

**Comment by JeongUijeong** [comment]
index.adoc을 꾸민다는 게 각 도메인 API Docs로 연결되는 링크를 건다는 말씀이실까요? ㅎㅎ
adoc은 각 도메인별로 나누는 게 좋을 것 같아요~~

**Comment by wocjf0513** [comment]
의정님이 하신대로 도메인별로 나누고, index.adoc에 링크 걸거 같습니다. 꾸며야 된다는게 좀 애매하네요
