### ISSUE TITLE
issue: Open API에서 더 많은 정보 활용

### ISSUE THREAD

**Issue by JeongUijeong** [Shimpyo-House/Shimpyo_BE#87]
# Open API에서 더 많은 정보를 활용한다. 

### 1. Open API 추가 정보 불러오기

기존 보다 많은 정보를 사용하기 위해 Open API를 통해 추가 정보를 불러와 제공하도록 해야 합니다. 
추가로 제공할 정보는 아래와 같습니다. 

**< 추가될 정보 >**
<details>
<summary>숙박 상품 옵션 정보</summary>
<div>

- 객실 내 취사 여부
- 식음료장
- 문의 및 안내
- 주차시설
- 픽업 서비스
- 부대시설(기타)
</div>
</details>

<details>
<summary>숙박 상품 부대시설 정보</summary>
<div>

- 바비큐장여부
- 뷰티시설정보
- 식음료장여부
- 자전거대여여부
- 캠프파이어여부
- 휘트니스센터여부
- 노래방여부
- 공용샤워실여부
- 공용PC실여부
- 사우나실여부
- 세미나실여부
- 스포츠시설여부
</div>
</details>

<details>
<summary>객실 상품 옵션 정보</summary>
<div>

- 목욕 시설 여부
- 홈시어터 여부
- 에어컨 여부
- TV 여부
- PC 여부
- 케이블 설치 여부
- 인터넷 여부
- 냉장고 여부
- 세면도구 여부
- 소파 여부
- 취사 용품 여부
- 테이블 여부
- 드라이기 여부
</div>
</details>

<details>
<summary>객실 상품 이미지 정보</summary>
<div>

- 객실사진1
- 객실사진1 설명
- 객실사진2
- 객실사진2 설명
- 객실사진3
- 객실사진3 설명
- 객실사진4
- 객실사진4 설명
- 객실사진5
- 객실사진5 설명
</div>
</details>

---

### 2. 추가된 정보를 담기 위해 DB 설계 수정
추가적으로 사용하기로 한 정보를 토대로 DB를 재설계 해야 합니다. 
ERD Cloud 를 사용합니다. 링크: https://www.erdcloud.com/d/sy9ohadeJa3aMpuiL

---

### 3. DB 설계에 맞도록 Entity 수정
DB 재설계에 맞도록 Entity를 수정해야 합니다. 

**< 추가할 Entity(테이블)  >**
- Address: 숙박 상품 주소
- ProductOption: 숙박 상품 옵션
- Amenity: 숙박 상품 부대시설
- RoomOption: 객실 옵션
- RoomImage: 객실 사진
- RoomPrice: 객실 가격

## Todo
- [x] Open API에서 추가적으로 데이터 수집 후 저장
- [x] DB 재설계
- [x] Entity 추가

**Comment by wocjf0513** [comment]
정리 왤케 잘하능교...
